# Pre-commit hooks for Python code
# Last revision by: Joao Morado
# Last revision date: 08.Feb.2023
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ["--verbose"]
-   repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
    -   id: blackdoc
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
#        additional_dependencies: [flake8-docstrings]
        args: ["--ignore=E501,W503", --max-line-length=127]
        verbose: True
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--min-similarity-lines=81"]
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.0.0
#    hooks:
#    -   id: mypy
#        args: [--no-strict-optional, --ignore-missing-imports]
